-- Create table for items
CREATE TABLE "public"."items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "inventory_id" BIGINT NOT NULL,
    "name" VARCHAR(255) NOT NULL,
    "stock" INTEGER DEFAULT 0 NOT NULL,
    "price" NUMERIC(10,2) DEFAULT 0.00 NOT NULL,
    "platforms" JSONB DEFAULT '[]'::JSONB, -- Better than TEXT[]
    "image" TEXT,
    "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add foreign key for inventory_id
ALTER TABLE "public"."items"
ADD CONSTRAINT "items_inventory_id_fkey"
FOREIGN KEY ("inventory_id") REFERENCES "public"."inventories"("id") ON DELETE CASCADE;

-- Create index for faster inventory lookups
CREATE INDEX idx_items_inventory_id ON public.items(inventory_id);
