-- Create sequence for items
CREATE SEQUENCE "public"."items_id_seq";

-- Create table for inventories
CREATE TABLE "public"."inventories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" UUID,
    "name" CHARACTER VARYING(255) NOT NULL,
    "description" TEXT,
    "parent_inventory_id" BIGINT,
    "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create unique index for inventories
CREATE UNIQUE INDEX inventory_pkey ON public.inventories USING btree (id);

-- Add primary key constraint to inventories
ALTER TABLE "public"."inventories" ADD CONSTRAINT "inventory_pkey" PRIMARY KEY USING INDEX "inventory_pkey";

-- Add foreign key for parent_inventory_id referencing inventories
ALTER TABLE "public"."inventories" ADD CONSTRAINT "inventories_parent_inventory_id_fkey" 
FOREIGN KEY (parent_inventory_id) REFERENCES inventories(id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."inventories" VALIDATE CONSTRAINT "inventories_parent_inventory_id_fkey";

-- Add foreign key for user_id referencing auth.users
ALTER TABLE "public"."inventories" ADD CONSTRAINT "inventories_user_id_fkey" 
FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."inventories" VALIDATE CONSTRAINT "inventories_user_id_fkey";

-- Grant permissions on inventories table
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventories" TO "anon";
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventories" TO "authenticated";
GRANT DELETE, INSERT, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."inventories" TO "service_role";
