-- INSERT INTO public.available_integrations (id, platform_name, authentication_method, description, status)
-- VALUES
--     ('aaaa1111-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'eBay', 'API Key', 'Sell on eBay with real-time inventory sync', 'active'),
--     ('bbbb2222-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Amazon', 'OAuth', 'Manage Amazon listings and orders', 'active'),
--     ('cccc3333-cccc-cccc-cccc-cccccccccccc', 'Shopify', 'OAuth', 'Sync Shopify store inventory and sales', 'active');
